#设置运行端口
server:
  port: 9091

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=educationsystem;encrypt=true;trustServerCertificate=true
#    url: jdbc:sqlserver://localhost:1433;databaseName=educationsystem
    username: HYGGE
    password: zxcvbn

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/educationsystem?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
#    username: root
#    password: 123456